development:
  adapter: postgresql
  database: github-counter_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: github-counter_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: github-counter_production
  pool: 5
  timeout: 5000
